application: sopay-me
# When testing, use version: 'id-test'.  To publish, change to 'live' but do not
# sumbit back to source control with 'version: live'. Source control should
# always be 'test' to prevent accidentally deploying tests to live traffic.
version: main
runtime: python
api_version: 1

default_expiration: 0

handlers:
- url: /static
  static_dir: static
- url: /task/.*
  script: main.py
  login: admin
- url: /admin.*
  script: main.py
  login: admin
- url: /.*
  script: main.py
