application: sopay-me
version: zpm-test
runtime: python
api_version: 1

default_expiration: 0

handlers:
- url: /static
  static_dir: static
- url: /task/.*
  script: main.py
  login: admin
- url: /.*
  script: main.py