application: sopay-me
# In version control and testing, use version: 'id-test'.  To publish, change to
# 'live' but do not sumbit back to source control with 'version: live'
version: cgibbs-test
runtime: python
api_version: 1

default_expiration: 0

handlers:
- url: /static
  static_dir: static
- url: /task/.*
  script: main.py
  login: admin
- url: /.*
  script: main.py
