from google.appengine.ext import db


class SPMUser(db.Model):

  google_account = db.UserProperty()
  # facebook_account = db.StringProperty()

  name = db.StringProperty()
  email = db.StringProperty()
  facebook_id = db.StringProperty()
  
  checkout_verified = db.BooleanProperty()
  checkout_last_sync = db.DateTimeProperty()
  checkout_merchant_id = db.StringProperty()
  checkout_merchant_secret = db.StringProperty()
  
  last_login = db.DateTimeProperty()


class PurchaseRecord(db.Model):

  # created using the seller SPMUser object as parent, also recorded here:
  SPMUser_seller = db.ReferenceProperty(
    reference_class = SPMUser,
    collection_name = 'seller_spmuid'
  )
  SPMUser_buyer = db.ReferenceProperty(
    reference_class = SPMUser,
    collection_name = 'buyer_spmuid'
  )
  SPMUser_sentto = db.ReferenceProperty(
    reference_class = SPMUser,
    collection_name = 'payer_spmuid'
  )

  # these are not required, since we sync non-sopayme things.  all three must
  # both be present for all sopayme-originating payments
  spm_name = db.StringProperty()
  spm_serial = db.IntegerProperty()
  spm_transaction = db.IntegerProperty()

  date_latest = db.DateTimeProperty()
  date_sent = db.DateTimeProperty()
  # date_accepted = db.DateTimeProperty()
  date_paid = db.DateTimeProperty()

  amount = db.StringProperty()
  currency = db.StringProperty()
  description = db.StringProperty()
  # sent to email is set when spm creates the record (OR) when the field is
  # empty and we get an email address from the checkout updates
  sent_to_email = db.StringProperty()

  # the following keep track of information that we get from checkout requests;
  # any information that is generated by this application is not kept in a
  # checkout_ prefixed field
  checkout_key = db.StringProperty()
  checkout_payurl = db.StringProperty()
  checkout_buyer_id = db.StringProperty()
  checkout_buyer_name = db.StringProperty()
  checkout_buyer_email = db.StringProperty()
  checkout_merchant_id = db.StringProperty()


class CountStore(db.Model):

  # created using 'fake' parent keyed off of spm_name
  url_count = db.IntegerProperty(required = True)